[features]
seeds = false
[programs.localnet]
staking = "FffsMRFu9vFMfkTN4AGDfdSfwJmyN2ofFJGXTqhokv3o"

[programs.devnet]
staking = "FffsMRFu9vFMfkTN4AGDfdSfwJmyN2ofFJGXTqhokv3o"

[programs.mainnet]
staking = "FffsMRFu9vFMfkTN4AGDfdSfwJmyN2ofFJGXTqhokv3o"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/phongvu/.config/solana/phantom.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
