[features]
seeds = false
[programs.localnet]
staking = "A8FEb1JeMfwtVtqjjE1txZaFWTVd1e3vgio7qiMyufsC"

[programs.devnet]
staking = "A8FEb1JeMfwtVtqjjE1txZaFWTVd1e3vgio7qiMyufsC"

[programs.mainnet]
staking = "A8FEb1JeMfwtVtqjjE1txZaFWTVd1e3vgio7qiMyufsC"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "mainnet"
wallet = "/Users/amitkolambikar/.config/solana/phantomWallet.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
